"""empty message

Revision ID: 15f6e878b176
Revises: 22e50e709bfc
Create Date: 2021-10-23 23:34:23.462517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15f6e878b176'
down_revision = '22e50e709bfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body', sa.Text(), nullable=True))
    op.drop_column('posts', 'text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('posts', 'body')
    # ### end Alembic commands ###
