"""empty message

Revision ID: 3395ab6f00f9
Revises: f82ecfa77f95
Create Date: 2021-10-24 00:11:53.338199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3395ab6f00f9'
down_revision = 'f82ecfa77f95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('resume', sa.String(length=255), nullable=True))
    op.execute("UPDATE posts set resume = 'Resume not set'")
    op.execute("UPDATE posts set body = 'Body not set' WHERE body is null")
    op.alter_column('posts', 'resume', nullable=False)
    op.alter_column('posts', 'body',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'body',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('posts', 'resume')
    # ### end Alembic commands ###
