"""empty message

Revision ID: b940f6a6b3c7
Revises: d25a65066658
Create Date: 2021-10-19 13:31:30.764019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b940f6a6b3c7'
down_revision = 'd25a65066658'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image__mime_type', sa.String(length=1016), nullable=True))
    op.add_column('posts', sa.Column('image__ext', sa.String(length=1010), nullable=True))
    op.add_column('posts', sa.Column('image__file_name', sa.String(length=1016), nullable=True))
    op.drop_column('posts', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('posts', 'image__file_name')
    op.drop_column('posts', 'image__ext')
    op.drop_column('posts', 'image__mime_type')
    # ### end Alembic commands ###
