"""empty message

Revision ID: f82ecfa77f95
Revises: 15f6e878b176
Create Date: 2021-10-23 23:43:29.711912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f82ecfa77f95'
down_revision = '15f6e878b176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.String(), nullable=True))
    op.execute("UPDATE posts set title = 'Title not set'")
    op.alter_column('posts', 'title', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'title')
    # ### end Alembic commands ###
